### ISSUE TITLE
afterEvaluate deprecated in Gradle 6; will not work in 7+

### ISSUE THREAD

**Issue by gillius** [palantir/gradle-git-version#353]
https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated

Stacktrace when using Gradle 6.3 and gradle-git-version 0.12.3

```
Using method Project.afterEvaluate(Closure) when the project is already evaluated has been deprecated. This will fail with an error in Gradle 7.0. The configuration given is ignored because the project has already been evaluated. To apply this configuration, remove afterEvaluate. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated
        at org.gradle.api.internal.project.DefaultProject.maybeNagDeprecationOfAfterEvaluateAfterProjectIsEvaluated(DefaultProject.java:1031)
        at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1021)
        at org.gradle.api.Project$afterEvaluate.call(Unknown Source)
        at com.palantir.gradle.gitversion.BuildScanPluginInterop.addBuildScanCustomValues(BuildScanPluginInterop.groovy:26)
        at com.palantir.gradle.gitversion.GitVersionRootPlugin.apply(GitVersionRootPlugin.java:34)
        at com.palantir.gradle.gitversion.GitVersionRootPlugin.apply(GitVersionRootPlugin.java:26)
```

**Comment by yatsvic** [comment]
From Gradle v7.0.0-M3
```* What went wrong:
An exception occurred applying plugin request [id: 'com.palantir.git-version']
> Failed to apply plugin class 'com.palantir.gradle.gitversion.GitVersionRootPlugin'.
   > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

**Comment by tunix** [comment]
gradle 7.0.2 is now the stable version.

**Comment by JohnAmican** [comment]
Getting the same issue with gradle 7.0.2:

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.palantir.git-version', version: '0.12.3']
> Failed to apply plugin class 'com.palantir.gradle.gitversion.GitVersionRootPlugin'.
   > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
```

Let me know if you need more detail.

**Comment by xianzheTM** [comment]
Are there any alternatives?

**Comment by eplarson** [comment]
Discussion thread with some background on why `afterEvaluate` was deprecated and now throws errors: https://github.com/gradle/gradle/issues/1135

**Comment by flyaruu** [comment]
So any progress here? If I understand correctly palantir does not work at all in Gradle 7, this is going to bite a lot of people. At least we should clearly mark that it doesn't work.

**Comment by JohnAmican** [comment]
Our project only needed the hash. FWIW it was easy enough to port over just that functionality from https://github.com/palantir/gradle-git-version/blob/develop/src/main/java/com/palantir/gradle/gitversion/VersionDetailsImpl.java into our buildSrc:

```
fun Project.getProjectGitHashFull(): String {
    val gitRepo = gitRepo(this)
    return getGitHashFull(gitRepo)
}

private fun getGitHashFull(git: Git): String {
    val objectId: ObjectId = git.repository.findRef(HEAD).objectId
    return objectId.name()
}

private fun gitRepo(project: Project): Git {
    return try {
        val gitDir: File = getRootGitDir(project.projectDir)
        wrap(FileRepository(gitDir))
    } catch (e: IOException) {
        throw RuntimeException(e)
    }
}

private fun getRootGitDir(currentRoot: File): File {
    val gitDir: File = scanForRootGitDir(currentRoot)
    require(gitDir.exists()) { "Cannot find '.git' directory" }
    return gitDir
}

private fun scanForRootGitDir(currentRoot: File): File {
    val gitDir = File(currentRoot, ".git")
    if (gitDir.exists()) {
        return gitDir
    }

    // stop at the root directory, return non-existing File object;
    return if (currentRoot.parentFile == null) {
        gitDir
    } else scanForRootGitDir(currentRoot.parentFile)

    // look in parent directory;
}
```

...and add a dependency on `org.eclipse.jgit`.

It looks like `afterEvaluate` is only used for build scans, so if your use case is simpler I imagine it's easy enough to copy+paste just what you need, or fork this project and remove the use of `afterEvaluate`

**Comment by alecbarber** [comment]
The call to `afterEvaluate` was added in #329 for build scans, which is only present in v0.12.3. Rolling back to version v0.12.2 fixed this issue for me.

**Comment by bmarcaur** [comment]
Can someone link to a repo that is exhibiting this behavior?

We have a ton of repos on gradle 7+ and git-version 0.12.3 that are working without issue. Here is a public example:

Gradle 7.3:
https://github.com/palantir/proxy-processor/blob/develop/gradle/wrapper/gradle-wrapper.properties#L3
Git-version 0.12.3:
https://github.com/palantir/proxy-processor/blob/develop/build.gradle#L12

To sanity check I did the following, stolen mostly from [here](https://docs.gradle.org/current/userguide/troubleshooting.html#sec:troubleshooting_build_logic):
* Checked out this repo
* Set it up in Intellij
* Ran the following: `./gradlew printVersion -Dorg.gradle.debug=true --no-daemon`
* Remote debug'd the code on `5005` using Intellij remote debugging
* Set a breakpoint on the [afterEvaluate line](https://github.com/palantir/gradle-git-version/blob/develop/src/groovy/groovy/com/palantir/gradle/gitversion/BuildScanPluginInterop.groovy#L26)
* Traced down until it hit the [afterEvaluate inside Gradle](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java#L1056)
* Then I noticed that the "failure" is only in a specific state of using `afterEvaluate` when the project is already evaluated. Which I think means that our common setup, [example](https://github.com/palantir/proxy-processor/blob/develop/build.gradle#L23), evaluates at a time where the `rootProject` is still evaluating. Specifically the conditional `this.state.isConfiguring()` was `true` for my test case and thus did not actually error.
* This allowed the code to continue in to the closure and finish without error.

I hope that helps. I suspect that using the `gitVersion` at differing stages of the setup process might cause the behavior you are experiencing.


Edit:
Someone DM'd me a repro repository and the shape of the issue was as follows. Turns out that my suspicions were correct. `git-version` cannot be used to determine the version on a per sub-gradle-module basis. Being that it derives its version from the "global" encasing git, all versions of all modules must logically be the same. As such we always bootstrap this plugin in the the root `build.gradle` (by convention). Thus our usage of `afterEvaluate` always succeeds because it happens before the `rootProject` has finished evaluating, however loading the plugin in submodules happens... after evaluation of the root project. So if you are loading the plugin in a submodule simply move the plugin load to the root build.gradle, load and set the version, and then referenced the root project for your submodule version.

```gradle
// Root build.gradle
plugins {
	id 'com.palantir.git-version' version '0.12.3'
}

group = 'com.example'
version = gitVersion()

// submodule build.gradle
version = rootProject.version
```

**Comment by lapo-luchini** [comment]
> Can someone link to a repo that is exhibiting this behavior?

Didn't happen to me in any single-project repo, but happened as soon as it [became multi-project](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html).

**Comment by bmarcaur** [comment]
Putting my edit as a comment so it is obvious how to fix this in multi-project repos.

Someone DM'd me a repro repository and the shape of the issue was as follows. Turns out that my suspicions were correct. `git-version` cannot be used to determine the version on a per sub-gradle-module basis. Being that it derives its version from the "global" encasing git, all versions of all modules must logically be the same. As such we always bootstrap this plugin in the the root `build.gradle` (by convention). Thus our usage of `afterEvaluate` always succeeds because it happens before the `rootProject` has finished evaluating, however loading the plugin in submodules happens... after evaluation of the root project. So if you are loading the plugin in a submodule simply move the plugin load to the root build.gradle, load and set the version, and then referenced the root project for your submodule version.

```gradle
// Root build.gradle
plugins {
	id 'com.palantir.git-version' version '0.12.3'
}

group = 'com.example'
version = gitVersion()

// submodule build.gradle
version = rootProject.version
```

**Comment by bmarcaur** [comment]
So now that #541 is closed the original submodule instantiation should be handled more gracefully.
