### ISSUE TITLE
Disable appending 'dirty' status

### ISSUE THREAD

**Issue by jmayday** [palantir/gradle-git-version#82]
Is it possible to disable appending 'dirty' status easier that by code below?

```
def details = versionDetails()
version = details.lastTag + (details.commitDistance.toString() != '0' ? ('-' + details.commitDistance) : '')
```

**Comment by iamdanfox** [comment]
Most users of this plugin want that `.dirty` so that they can immediately catch a dirty publish or see whether a local artifact was reproducible etc. I don't think this plugin will accept changes to make that configurable.

The verbose workaround you mention would technically work, but personally I'd try to eliminate the root cause - why do you want to hide the fact that the repository is dirty... could you use .gitignores instead?

**Comment by jmayday** [comment]
You're totally right @iamdanfox. Somehow I forgot to make sure my repo is really clean (IntelliJ IDEA was showing nothing to commit). ```git status``` revealed the truth about current state of my local repo.
