### ISSUE TITLE
versionDetails() should include date of the commit

### ISSUE THREAD

**Issue by xenomachina** [palantir/gradle-git-version#84]
I'm currently doing something like this:

``` groovy
def gitDate() {
    return 'git show -s --format=%cd --date=short'.execute().text.trim()
}
version "${gitDate()}-${gitVersion()}"
```

This gives me a rough idea of the age of each version. It would be great if I could do this without having to call out to `git` myself.

**Comment by iamdanfox** [comment]
I don't think that's a version format that we want to advocate with this plugin - the convention we're pushing is that normal clean tagged releases are semver compatible `major.minor.patch` strings, then you get some extra helpful info for when you're not on a tagged release.

If you want to offroad, then I think the snippet you've got is OK because visually, it emphasises there's a bit of extra git funkiness going on.

**Comment by xenomachina** [comment]
That's fair!

For what it's worth I'm not doing this with libraries, where I do stick to semver compatible `major.minor.patch` version numbers, but for web apps where I really just need a unique string that I can track back to a specific git commit.

**Comment by iamdanfox** [comment]
@xenomachina we use this for our web-apps too, and you do get a unique string that you can trace back to a git commit, for example, the last four commits on an internal project published artifacts with the following versions:

```
8.55.1
8.55.0-2-g0018f3f
8.55.0-1-gbd2dfea
8.55.0
```
