### ISSUE TITLE
Fallback to jgit if git command doesn't exist

### ISSUE THREAD

**Issue by delta003** [palantir/gradle-git-version#85]
Any objections to adding fallback to jgit if `GitCli.verifyGitCommandExists()` fails [here](https://github.com/palantir/gradle-git-version/blob/develop/src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy#L87)?
@iamdanfox @uschi2000

**Comment by delta003** [comment]
Additionally, plugin doesn't work with jgit as git client (installed jgit but aliased as git):
`fatal: "--tags" is not a valid option`

I was thinking we can also run `git --version` after check that git exists to make sure we're running on git.

Otherwise just fall back to implementation before we switched to calling into installed git.

**Comment by iamdanfox** [comment]
@delta003 as mentioned over slack, I'm amenable to this only if we can run some integration tests to verify this works in the scenario you described (`git` aliased to run `jgit`).  This might require some refactoring, happy to work with you on this.

To be honest, I think the preferable approach would be to fix the environment you're using - otherwise I'm concerned we'll open ourselves up to an explosion of edge-cases and testing.

**Comment by helenyuyu** [comment]
Unfortunately we don't have control over a lot of the environments in which we want to use gradle-git-version, and we've run into a lot of issues with git not being installed in on-prem environments.
